import Head from "next/head";
import React from 'react';
import Sidebar from './components/sidebar';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import List from './components/list';
import Box from "@mui/material/Box";
import CssBaseline from '@mui/material/CssBaseline';
// import PrimarySearchAppBar from "./components/navbar";

export default function Home() {
  return (
    <Box sx={{ display: 'flex' }}>
      <CssBaseline />
      {/* <PrimarySearchAppBar sx={{ width: `calc(100% - 18%)`, ml: `18%` }} /> */}

      <Box
        component="main"
        sx={{ flexGrow: 1, bgcolor: 'background.default', p: 3, ml: 25 }}
      >

      <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <List/>
      </main>
      
    </div>
    </Box>
      <div>
      <Sidebar />
      </div>
    
    </Box>
    
  );
}
